export enum NotificationType {
    REQUEST_FOR_PRODUCT= "REQUEST_FOR_PRODUCT",
    ACCEPT_REQUEST_FOR_PRODUCT = "ACCEPT_REQUEST_FOR_PRODUCT",
    REFUSE_REQUEST_FOR_PRODUCT= "REFUSE_REQUEST_FOR_PRODUCT",
    CONFIRM_THE_RECIPE_OF_PRODUCT= "CONFIRM_THE_RECIPE_OF_PRODUCT",
}
